import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Inter } from "next/font/google"; // fonts
import { Container, SSRProvider } from "@/components/bootstrap";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    // this is where we can set up metadata now (instead of HTML)
    title: "Zukkii-JS", // <-- Title of page
    description: "Generated by create next app", // <-- Don't show on screen but useful when being searched
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            {/* font can be specificed here */}
            <body className={inter.className}>
                <SSRProvider>
                    <NavBar />
                    <main>
                        <Container className="py-4">{children}</Container>
                    </main>
                </SSRProvider>
            </body>
        </html>
    );
}
